---
replicas: 1
minimumMasterNodes: 1

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: es
  resources:
    requests:
      storage: 30Gi

nodeSelector:
  nodetype: monitoring
tolerations:
 - key: "nodetype"
   operator: "Equal"
   value: "monitoring"
   effect: "NoSchedule"